# Generated by Django 5.1.4 on 2025-08-19 08:01

import apps.events.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventservice',
            name='id',
            field=models.CharField(default=apps.events.models.generate_unique_id, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventservicedetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
