# Generated by Django 5.1.4 on 2025-08-19 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventservice_id_alter_eventservicedetail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventservicedetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
