# Generated by Django 5.1.4 on 2025-08-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventservicedetail_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='event',
            name='total_reviews',
        ),
    ]
