# Generated by Django 5.1.4 on 2025-09-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='full_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='is_fully_paid',
            field=models.BooleanField(default=False),
        ),
    ]
