# Generated by Django 5.1.4 on 2025-09-16 04:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_serviceorder_full_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='buyer_agreed',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
