# Generated by Django 5.2.7 on 2026-07-19 04:57

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_services', '0002_alter_eventservice_service_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_bson_id, editable=False, max_length=24, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('customer_note', models.TextField(blank=True, help_text='Additional information provided by the customer.', null=True)),
                ('seller_note', models.TextField(blank=True, help_text="Seller's response or explanation.", null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_hires', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.PROTECT, related_name='customer_hires', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hire_requests', to='event_services.eventservice')),
            ],
            options={
                'verbose_name': 'Hire Request',
                'verbose_name_plural': 'Hire Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HireBookingSlot',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_bson_id, editable=False, max_length=24, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField(db_index=True, help_text='Event starting date and time.')),
                ('ends_at', models.DateTimeField(db_index=True, help_text='Event ending date and time.')),
                ('venue_name', models.CharField(blank=True, help_text='Example: Grand Palace Convention Hall.', max_length=255, null=True)),
                ('venue_address', models.TextField(help_text='Full event location or address.')),
                ('location_note', models.TextField(blank=True, help_text='Optional directions or location instructions.', null=True)),
                ('hire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_slots', to='hires.hire')),
            ],
            options={
                'verbose_name': 'Hire Booking Slot',
                'verbose_name_plural': 'Hire Booking Slots',
                'ordering': ['starts_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hire',
            index=models.Index(fields=['customer', 'status'], name='hires_hire_custome_d0ba58_idx'),
        ),
        migrations.AddIndex(
            model_name='hire',
            index=models.Index(fields=['service', 'status'], name='hires_hire_service_016d43_idx'),
        ),
        migrations.AddIndex(
            model_name='hire',
            index=models.Index(fields=['status', 'created_at'], name='hires_hire_status_660518_idx'),
        ),
        migrations.AddIndex(
            model_name='hirebookingslot',
            index=models.Index(fields=['hire', 'starts_at'], name='hires_hireb_hire_id_9a96d1_idx'),
        ),
        migrations.AddIndex(
            model_name='hirebookingslot',
            index=models.Index(fields=['starts_at', 'ends_at'], name='hires_hireb_starts__d7f0b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='hirebookingslot',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='hire_slot_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='hirebookingslot',
            constraint=models.UniqueConstraint(fields=('hire', 'starts_at', 'ends_at'), name='unique_time_slot_per_hire'),
        ),
    ]
