# Generated by Django 5.2.7 on 2026-08-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hires', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hirebookingslot',
            name='hire_slot_end_after_start',
        ),
        migrations.RemoveConstraint(
            model_name='hirebookingslot',
            name='unique_time_slot_per_hire',
        ),
        migrations.RemoveIndex(
            model_name='hirebookingslot',
            name='hires_hireb_starts__d7f0b3_idx',
        ),
        migrations.RemoveField(
            model_name='hirebookingslot',
            name='ends_at',
        ),
        migrations.AddField(
            model_name='hirebookingslot',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Customer WhatsApp number.', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='hirebookingslot',
            index=models.Index(fields=['starts_at'], name='hires_hireb_starts__aabc2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='hirebookingslot',
            constraint=models.UniqueConstraint(fields=('hire', 'starts_at'), name='unique_time_slot_per_hire'),
        ),
    ]
