# Generated by Django 5.2.7 on 2026-08-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hires', '0002_remove_hirebookingslot_hire_slot_end_after_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirebookingslot',
            name='google_map_link',
            field=models.URLField(blank=True, help_text='Optional Google Maps shared location link.', max_length=500, null=True),
        ),
    ]
