# Generated by Django 5.2.7 on 2026-08-14 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hires', '0003_hirebookingslot_google_map_link'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='event_type',
            field=models.CharField(blank=True, choices=[('holud', 'Holud'), ('mehedi', 'Mehedi'), ('akhd_walima', 'Akhd/Walima'), ('wedding_ceremony', 'Wedding Ceremony'), ('reception', 'Reception'), ('anniversary', 'Anniversary'), ('birthday', 'Birthday')], db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hire',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hire_requests', to='packages.servicepackage'),
        ),
        migrations.AddField(
            model_name='hire',
            name='package_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hire',
            name='package_title_snapshot',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
