# Generated by Django 5.2.7 on 2026-08-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hires', '0004_hire_event_type_hire_package_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hirebookingslot',
            name='hires_hireb_hire_id_9a96d1_idx',
        ),
        migrations.RemoveIndex(
            model_name='hirebookingslot',
            name='hires_hireb_starts__aabc2c_idx',
        ),
        migrations.RemoveField(
            model_name='hirebookingslot',
            name='location_note',
        ),
        migrations.RemoveField(
            model_name='hirebookingslot',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='hire',
            name='customer_whatsapp_number',
            field=models.CharField(blank=True, help_text='Customer WhatsApp number for this hire request.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hirebookingslot',
            name='event_type',
            field=models.CharField(blank=True, choices=[('holud', 'Holud'), ('mehedi', 'Mehedi'), ('akhd_walima', 'Akhd/Walima'), ('wedding_ceremony', 'Wedding Ceremony'), ('reception', 'Reception'), ('anniversary', 'Anniversary'), ('birthday', 'Birthday')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hirebookingslot',
            name='starts_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Event starting date and time.', null=True),
        ),
        migrations.AlterField(
            model_name='hirebookingslot',
            name='venue_address',
            field=models.TextField(blank=True, help_text='Full event location or address.', null=True),
        ),
        migrations.AddConstraint(
            model_name='hirebookingslot',
            constraint=models.UniqueConstraint(fields=('hire', 'event_type'), name='unique_event_type_per_hire'),
        ),
    ]
