# Generated by Django 5.2.7 on 2026-08-15 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hires', '0005_remove_hirebookingslot_hires_hireb_hire_id_9a96d1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of bookings for the selected normal service or package.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
