# Generated by Django 5.2.7 on 2026-08-15 12:23

import apps.core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hires', '0006_hire_quantity'),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireBookingItem',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_bson_id, editable=False, max_length=24, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('package_title_snapshot', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('package_price_snapshot', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Hire Booking Item',
                'verbose_name_plural': 'Hire Booking Items',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='hirebookingslot',
            name='unique_event_type_per_hire',
        ),
        migrations.AlterField(
            model_name='hire',
            name='customer_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hire',
            name='customer_whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hire',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='hire',
            name='seller_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hirebookingslot',
            name='google_map_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hirebookingslot',
            name='starts_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='hirebookingslot',
            name='venue_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hirebookingslot',
            name='venue_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hirebookingitem',
            name='hire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_items', to='hires.hire'),
        ),
        migrations.AddField(
            model_name='hirebookingitem',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hire_booking_items', to='packages.servicepackage'),
        ),
        migrations.AddField(
            model_name='hirebookingslot',
            name='booking_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_slots', to='hires.hirebookingitem'),
        ),
        migrations.AddConstraint(
            model_name='hirebookingslot',
            constraint=models.UniqueConstraint(fields=('booking_item', 'event_type'), name='unique_event_type_per_booking_item'),
        ),
        migrations.AddConstraint(
            model_name='hirebookingitem',
            constraint=models.UniqueConstraint(condition=models.Q(('package__isnull', False)), fields=('hire', 'package'), name='unique_package_per_hire'),
        ),
        migrations.AddConstraint(
            model_name='hirebookingitem',
            constraint=models.UniqueConstraint(condition=models.Q(('package__isnull', True)), fields=('hire',), name='one_normal_service_item_per_hire'),
        ),
    ]
