# Generated by Django 5.2.7 on 2026-08-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hires', '0007_hirebookingitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='event_type',
            field=models.CharField(blank=True, choices=[('holud', 'Holud'), ('mehedi', 'Mehedi'), ('akhd_walima', 'Akhd/Walima'), ('wedding_ceremony', 'Wedding Ceremony'), ('reception', 'Reception'), ('anniversary', 'Anniversary'), ('birthday', 'Birthday'), ('others', 'Others')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hirebookingslot',
            name='event_type',
            field=models.CharField(blank=True, choices=[('holud', 'Holud'), ('mehedi', 'Mehedi'), ('akhd_walima', 'Akhd/Walima'), ('wedding_ceremony', 'Wedding Ceremony'), ('reception', 'Reception'), ('anniversary', 'Anniversary'), ('birthday', 'Birthday'), ('others', 'Others')], db_index=True, max_length=20, null=True),
        ),
    ]
