# Generated by Django 5.2.7 on 2026-04-10 12:23

import apps.core.models
import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_planner', '0003_alter_eventbrand_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventService',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_bson_id, editable=False, max_length=24, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_name', models.CharField(choices=[('photography', 'Photography'), ('videography', 'Videography'), ('stage_designer', 'Stage Designer'), ('sound_lighting', 'Sound System and Lighting'), ('dj', 'DJ')], db_index=True, max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('cover_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('drive_link', models.URLField(blank=True, help_text='Google Drive or YouTube URL where applicable.', null=True)),
                ('shift_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('shift_hour', models.PositiveIntegerField(blank=True, help_text='Used for Photography, Videography, DJ.', null=True)),
                ('sound_system_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Used for Sound System and Lighting.', max_digits=10, null=True)),
                ('lighting_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Used for Sound System and Lighting.', max_digits=10, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='event_planner.eventbrand')),
            ],
            options={
                'verbose_name': 'Event Service',
                'verbose_name_plural': 'Event Services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceGalleryImage',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_bson_id, editable=False, max_length=24, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='event_services.eventservice')),
            ],
            options={
                'verbose_name': 'Service Gallery Image',
                'verbose_name_plural': 'Service Gallery Images',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='eventservice',
            index=models.Index(fields=['service_name'], name='event_servi_service_b55e29_idx'),
        ),
        migrations.AddIndex(
            model_name='eventservice',
            index=models.Index(fields=['slug'], name='event_servi_slug_c380d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventservice',
            constraint=models.UniqueConstraint(fields=('brand', 'service_name'), name='unique_service_name_per_brand'),
        ),
    ]
