# Generated by Django 5.2.7 on 2026-07-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventservice',
            name='service_name',
            field=models.CharField(choices=[('photography', 'Photography'), ('videography', 'Videography'), ('stage_designer', 'Stage Designer'), ('sound_lighting', 'Sound System and Lighting'), ('event_hall', 'Event Hall')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='eventservice',
            name='shift_hour',
            field=models.PositiveIntegerField(blank=True, help_text='Used for Photography, Videography, Hall booking service.', null=True),
        ),
    ]
