# Generated by Django 5.2.7 on 2026-07-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_services', '0002_alter_eventservice_service_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventservice',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
