# Generated by Django 5.2.7 on 2026-08-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_services', '0003_alter_eventservice_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventservice',
            name='lighting_payment',
        ),
        migrations.RemoveField(
            model_name='eventservice',
            name='sound_system_payment',
        ),
    ]
