# Generated by Django 5.2.7 on 2026-08-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_services', '0004_remove_eventservice_lighting_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventservice',
            name='rating_sum',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='eventservice',
            name='review_count',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
