# Generated by Django 5.2.7 on 2026-08-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_services', '0005_eventservice_rating_sum_eventservice_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventservice',
            name='shift_hour',
            field=models.PositiveIntegerField(blank=True, help_text='Used for Photography and Videography services.', null=True),
        ),
    ]
