# Generated by Django 5.2.7 on 2026-08-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_services', '0006_alter_eventservice_shift_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventservice',
            name='report_count',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
