# Generated by Django 5.2.7 on 2026-08-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_services', '0007_eventservice_report_count'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eventservice',
            name='event_servi_service_b55e29_idx',
        ),
        migrations.RemoveIndex(
            model_name='eventservice',
            name='event_servi_slug_c380d9_idx',
        ),
    ]
