# Generated by Django 5.2.7 on 2026-08-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_services', '0008_remove_eventservice_event_servi_service_b55e29_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventservice',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
