# Generated by Django 5.2.7 on 2026-07-27 05:55

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_bson_id, editable=False, max_length=24, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('issue_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('due_payment_last_date', models.DateField(db_index=True, help_text='The final date for paying the remaining amount.')),
                ('service_price', models.DecimalField(decimal_places=2, help_text='The agreed service price before discount.', max_digits=12)),
                ('discount_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('advance_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Advance amount already paid by the customer.', max_digits=12)),
                ('customer_name_snapshot', models.CharField(editable=False, max_length=255)),
                ('customer_email_snapshot', models.EmailField(editable=False, max_length=254)),
                ('customer_contact_snapshot', models.CharField(blank=True, editable=False, max_length=30)),
                ('seller_name_snapshot', models.CharField(editable=False, max_length=255)),
                ('seller_contact_snapshot', models.CharField(blank=True, editable=False, max_length=30)),
                ('brand_name_snapshot', models.CharField(editable=False, max_length=255)),
                ('service_name_snapshot', models.CharField(editable=False, max_length=255)),
                ('seller_note', models.TextField(blank=True, help_text='Optional invoice note or payment instructions.', null=True)),
                ('hire', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='hires.hire')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('service_price__gte', Decimal('0.00'))), name='invoice_service_price_non_negative'), models.CheckConstraint(condition=models.Q(('discount_price__gte', Decimal('0.00'))), name='invoice_discount_non_negative'), models.CheckConstraint(condition=models.Q(('advance_payment__gte', Decimal('0.00'))), name='invoice_advance_non_negative')],
            },
        ),
    ]
