# Generated by Django 5.2.7 on 2026-07-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_agreed',
            field=models.BooleanField(blank=True, default=None, help_text='Null means pending, True means agreed, and False means disagreed.', null=True),
        ),
    ]
