# Generated by Django 5.2.7 on 2026-08-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_customer_agreed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer_contact_snapshot',
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_whatsapp_snapshot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
