# Generated by Django 5.2.7 on 2026-08-06 03:41

import apps.invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_invoice_customer_contact_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='terms_conditions',
            field=models.JSONField(blank=True, default=list, help_text='Optional invoice terms and conditions. Maximum 3 bullet points are allowed.', validators=[apps.invoices.models.validate_terms_conditions]),
        ),
    ]
