# Generated by Django 5.2.7 on 2026-08-07 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_terms_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='shift_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of service shifts included in this invoice.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
