# Generated by Django 5.2.7 on 2026-08-07 14:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hires', '0003_hirebookingslot_google_map_link'),
        ('invoices', '0005_invoice_shift_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='shift_count',
        ),
        migrations.CreateModel(
            name='InvoiceSlotShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift_count', models.PositiveIntegerField(default=1, help_text='Number of shifts assigned to this booking slot.', validators=[django.core.validators.MinValueValidator(1)])),
                ('booking_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_slot_shift', to='hires.hirebookingslot')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_shifts', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Slot Shift',
                'verbose_name_plural': 'Invoice Slot Shifts',
                'ordering': ['booking_slot__starts_at'],
                'constraints': [models.UniqueConstraint(fields=('invoice', 'booking_slot'), name='unique_invoice_slot_shift')],
            },
        ),
    ]
