# Generated by Django 5.2.7 on 2026-08-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_remove_invoice_shift_count_invoiceslotshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='display_name_snapshot',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
    ]
