# Generated by Django 5.2.7 on 2026-08-14 11:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hires', '0004_hire_event_type_hire_package_and_more'),
        ('invoices', '0007_invoice_display_name_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='additional_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='additional_charge_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('additional_charge__gte', Decimal('0.00'))), name='invoice_additional_charge_non_negative'),
        ),
    ]
