# Generated by Django 5.2.7 on 2026-08-28 04:39

import apps.packages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepackage',
            name='short_info',
            field=models.JSONField(blank=True, default=list, validators=[apps.packages.models.validate_short_info]),
        ),
    ]
