# Generated by Django 5.2.7 on 2025-11-10 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('object_id', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_histories', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Slug history',
                'indexes': [models.Index(fields=['content_type', 'slug'], name='core_slughi_content_112f4f_idx')],
                'unique_together': {('content_type', 'object_id', 'slug')},
            },
        ),
    ]
