# Generated by Django 5.2.7 on 2025-11-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, help_text='Allowed: lowercase letters, numbers, hyphens', max_length=50, null=True, unique=True),
        ),
    ]
