# Generated by Django 5.2.7 on 2026-08-20 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_profile_image_url_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='office_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service_area',
        ),
    ]
