# Generated by Django 5.2.7 on 2026-04-07 11:02

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBrand',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_bson_id, editable=False, max_length=24, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(db_index=True, help_text='Unique public name for this event-service brand.', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('whatsapp_number', models.CharField(max_length=30)),
                ('service_area', models.CharField(help_text='City / region this brand primarily operates in.', max_length=255)),
                ('short_description', models.TextField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('seller', models.OneToOneField(limit_choices_to={'role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='event_brand', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Brand',
                'verbose_name_plural': 'Event Brands',
                'ordering': ['-created_at'],
            },
        ),
    ]
