# Generated by Django 5.2.7 on 2026-04-07 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventbrand',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='eventbrand',
            name='last_brand_name_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventbrand',
            name='brand_name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='eventbrand',
            name='service_area',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='EventBrandSlugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_history', to='event_planner.eventbrand')),
            ],
        ),
    ]
