# Generated by Django 5.2.7 on 2026-04-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0002_alter_eventbrand_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventbrand',
            options={'ordering': ['-created_at'], 'verbose_name': 'Event Brand', 'verbose_name_plural': 'Event Brands'},
        ),
        migrations.AlterModelOptions(
            name='eventbrandslughistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='eventbrand',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='eventbrand',
            name='last_brand_name_change',
        ),
        migrations.AddField(
            model_name='eventbrand',
            name='brand_name_last_changed',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last brand_name change.', null=True),
        ),
        migrations.AlterField(
            model_name='eventbrand',
            name='brand_name',
            field=models.CharField(db_index=True, help_text='Unique public name for this event-service brand.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='eventbrand',
            name='service_area',
            field=models.CharField(help_text='City / region this brand primarily operates in.', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='eventbrandslughistory',
            unique_together={('brand', 'old_slug')},
        ),
    ]
