# Generated by Django 5.2.7 on 2026-07-07 06:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0003_alter_eventbrand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbrand',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='brand_logo'),
        ),
    ]
