# Generated by Django 5.2.7 on 2026-07-29 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0004_eventbrand_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbrand',
            name='service_area',
        ),
        migrations.AddField(
            model_name='eventbrand',
            name='district',
            field=models.CharField(blank=True, db_index=True, help_text='District this brand primarily operates in.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eventbrand',
            name='division',
            field=models.CharField(blank=True, choices=[('dhaka', 'Dhaka'), ('chattogram', 'Chattogram'), ('khulna', 'Khulna'), ('rajshahi', 'Rajshahi'), ('rangpur', 'Rangpur'), ('barishal', 'Barishal'), ('sylhet', 'Sylhet'), ('mymensingh', 'Mymensingh')], db_index=True, help_text='Division this brand primarily operates in.', max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='eventbrand',
            index=models.Index(fields=['division', 'district'], name='event_plann_divisio_ee818d_idx'),
        ),
    ]
