# Generated by Django 5.2.7 on 2026-08-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0005_remove_eventbrand_service_area_eventbrand_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbrand',
            name='portfolio_link',
            field=models.URLField(blank=True, help_text='Optional Google Drive or YouTube portfolio URL.', null=True),
        ),
    ]
