# Generated by Django 5.2.7 on 2026-08-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0006_eventbrand_portfolio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbrand',
            name='brand_name_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eventbrand',
            name='brand_name',
            field=models.CharField(db_index=True, help_text='Public name for this event-service brand.', max_length=255),
        ),
    ]
