# Generated by Django 5.2.7 on 2026-08-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0007_eventbrand_brand_name_normalized_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbrand',
            name='brand_name_normalized',
        ),
        migrations.AlterField(
            model_name='eventbrand',
            name='brand_name',
            field=models.CharField(db_index=True, help_text='Unique public name for this event-service brand.', max_length=255, unique=True),
        ),
    ]
