# Generated by Django 5.2.7 on 2026-08-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0008_remove_eventbrand_brand_name_normalized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbrand',
            name='display_name',
            field=models.CharField(blank=True, db_index=True, help_text='Unique public-facing display name in Bangla or English.', max_length=255, null=True, unique=True),
        ),
    ]
