# Generated by Django 5.2.7 on 2026-08-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0009_eventbrand_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbrand',
            name='rating_sum',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='eventbrand',
            name='review_count',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
