# Generated by Django 5.2.7 on 2026-08-19 04:21

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0010_eventbrand_rating_sum_eventbrand_review_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eventbrand',
            name='event_plann_divisio_ee818d_idx',
        ),
        migrations.RemoveField(
            model_name='eventbrand',
            name='district',
        ),
        migrations.AlterField(
            model_name='eventbrand',
            name='division',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('dhaka', 'Dhaka'), ('chattogram', 'Chattogram'), ('khulna', 'Khulna'), ('rajshahi', 'Rajshahi'), ('rangpur', 'Rangpur'), ('barishal', 'Barishal'), ('sylhet', 'Sylhet'), ('mymensingh', 'Mymensingh')], max_length=30), blank=True, default=list, help_text='Divisions where this brand operates.', size=None),
        ),
        migrations.AddIndex(
            model_name='eventbrand',
            index=django.contrib.postgres.indexes.GinIndex(fields=['division'], name='eventbrand_divisions_gin'),
        ),
    ]
