# Generated by Django 5.2.7 on 2026-08-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0011_remove_eventbrand_event_plann_divisio_ee818d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbrand',
            name='office_address',
            field=models.TextField(blank=True, help_text='Optional office or business address.', max_length=500, null=True),
        ),
    ]
