# Generated by Django 5.2.7 on 2026-08-21 14:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0012_eventbrand_office_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbrand',
            name='division',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('whole_bangladesh', 'Whole Bangladesh'), ('dhaka', 'Dhaka'), ('chattogram', 'Chattogram'), ('khulna', 'Khulna'), ('rajshahi', 'Rajshahi'), ('rangpur', 'Rangpur'), ('barishal', 'Barishal'), ('sylhet', 'Sylhet'), ('mymensingh', 'Mymensingh')], max_length=30), blank=True, default=list, help_text='Divisions where this brand operates.', size=None),
        ),
    ]
