# Generated by Django 5.2.7 on 2026-08-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0013_alter_eventbrand_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbrand',
            name='short_description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
