# Generated by Django 5.2.7 on 2026-08-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_planner', '0014_alter_eventbrand_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbrand',
            name='short_description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
