# Generated by Django 5.1.4 on 2025-08-31 06:22

import apps.reports.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_remove_event_average_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(default=apps.reports.models.generate_report_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(db_index=True, max_length=100)),
                ('seller_full_name', models.CharField(max_length=301)),
                ('description', models.TextField(verbose_name='description')),
                ('user_full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('needs_more_info', 'Needs More Information')], db_index=True, default='pending', max_length=20)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='events.event')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
            },
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.report')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['brand_name'], name='reports_rep_brand_n_87877f_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['seller'], name='reports_rep_seller__c33149_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['event'], name='reports_rep_event_i_924c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter', 'event'], name='reports_rep_reporte_99745f_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reports_rep_status_c732ef_idx'),
        ),
        migrations.AddIndex(
            model_name='reportimage',
            index=models.Index(fields=['report'], name='reports_rep_report__78ff44_idx'),
        ),
    ]
