# Generated by Django 5.2.7 on 2026-08-12 10:12

import apps.core.models
import apps.reviews.models
import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hires', '0003_hirebookingslot_google_map_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(default=apps.core.models.generate_bson_id, editable=False, max_length=24, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(choices=[(2, '1.0'), (3, '1.5'), (4, '2.0'), (5, '2.5'), (6, '3.0'), (7, '3.5'), (8, '4.0'), (9, '4.5'), (10, '5.0')], help_text='Internal half-star representation: 2 = 1 star and 10 = 5 stars.')),
                ('comment', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[apps.reviews.models.validate_review_image], verbose_name='review_image')),
                ('hire', models.OneToOneField(help_text='The completed hire this review belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='review', to='hires.hire')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='review_created_desc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 2), ('rating__lte', 10)), name='review_rating_between_2_and_10')],
            },
        ),
    ]
