# Generated by Django 5.2.7 on 2026-08-16 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def cleanup_old_notifications(apps, schema_editor):
    """
    Existing notifications came from the old
    invoice-only notification system.

    New schema requires exactly one source:
        hire OR invoice.

    Remove legacy orphan notifications whose
    invoice no longer exists.
    """

    Notification = apps.get_model(
        "notifications",
        "Notification",
    )

    # Old orphan notifications have no invoice.
    # They cannot satisfy the new source constraint.
    Notification.objects.filter(
        invoice__isnull=True,
    ).delete()

    # Existing invoice notifications must use
    # invoice as their only source.
    Notification.objects.filter(
        invoice__isnull=False,
    ).update(
        hire=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "hires",
            "0007_hirebookingitem_and_more",
        ),
        (
            "invoices",
            "0008_invoice_additional_charge_and_more",
        ),
        (
            "notifications",
            "0001_initial",
        ),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="notification",
            name="notification_read_state_valid",
        ),

        migrations.RemoveIndex(
            model_name="notification",
            name="notif_recipient_read_idx",
        ),

        migrations.RenameIndex(
            model_name="notification",
            new_name="notif_rec_created_idx",
            old_name="notif_recipient_created_idx",
        ),

        migrations.AddField(
            model_name="notification",
            name="hire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=(
                    django.db.models.deletion.CASCADE
                ),
                related_name="notifications",
                to="hires.hire",
            ),
        ),

        migrations.AlterField(
            model_name="notification",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Small additional metadata required "
                    "by the frontend. Do not store complete "
                    "Hire or Invoice objects here."
                ),
            ),
        ),

        migrations.AlterField(
            model_name="notification",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=(
                    django.db.models.deletion.CASCADE
                ),
                related_name="notifications",
                to="invoices.invoice",
            ),
        ),

        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(
                default=False,
            ),
        ),

        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    (
                        "hire_created",
                        "New Hire Request",
                    ),
                    (
                        "invoice_created",
                        "Invoice Created",
                    ),
                    (
                        "invoice_updated",
                        "Invoice Updated",
                    ),
                ],
                max_length=50,
            ),
        ),

        # =============================================
        # IMPORTANT
        # Clean legacy data BEFORE new constraints.
        # =============================================

        migrations.RunPython(
            cleanup_old_notifications,
            migrations.RunPython.noop,
        ),

        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                condition=models.Q(
                    is_read=False,
                ),
                fields=[
                    "recipient",
                    "-created_at",
                ],
                name="notif_unread_rec_idx",
            ),
        ),

        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        is_read=False,
                        read_at__isnull=True,
                    )
                    |
                    models.Q(
                        is_read=True,
                        read_at__isnull=False,
                    )
                ),
                name="notif_read_state_chk",
            ),
        ),

        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        hire__isnull=False,
                        invoice__isnull=True,
                    )
                    |
                    models.Q(
                        hire__isnull=True,
                        invoice__isnull=False,
                    )
                ),
                name="notif_one_source_chk",
            ),
        ),

        migrations.AddConstraint(
            model_name="notification",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        hire__isnull=False,
                        invoice__isnull=True,
                        notification_type="hire_created",
                    )
                    |
                    models.Q(
                        hire__isnull=True,
                        invoice__isnull=False,
                        notification_type__in=[
                            "invoice_created",
                            "invoice_updated",
                        ],
                    )
                ),
                name="notif_type_source_chk",
            ),
        ),

        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    notification_type="hire_created",
                ),
                fields=(
                    "recipient",
                    "hire",
                    "notification_type",
                ),
                name="notif_unique_hire_created",
            ),
        ),

        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    notification_type="invoice_created",
                ),
                fields=(
                    "recipient",
                    "invoice",
                    "notification_type",
                ),
                name="notif_unique_invoice_created",
            ),
        ),
    ]