# Generated by Django 5.2.7 on 2026-08-17 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hires', '0007_hirebookingitem_and_more'),
        ('invoices', '0008_invoice_additional_charge_and_more'),
        ('notifications', '0002_remove_notification_notification_read_state_valid_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='notif_one_source_chk',
        ),
        migrations.RemoveConstraint(
            model_name='notification',
            name='notif_type_source_chk',
        ),
        migrations.AddField(
            model_name='notification',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reviews.review'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('hire_created', 'New Hire Request'), ('invoice_created', 'Invoice Created'), ('invoice_updated', 'Invoice Updated'), ('review_created', 'New Service Review')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hire__isnull', False), ('invoice__isnull', True), ('review__isnull', True)), models.Q(('hire__isnull', True), ('invoice__isnull', False), ('review__isnull', True)), models.Q(('hire__isnull', True), ('invoice__isnull', True), ('review__isnull', False)), _connector='OR'), name='notif_one_source_chk'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hire__isnull', False), ('invoice__isnull', True), ('notification_type', 'hire_created'), ('review__isnull', True)), models.Q(('hire__isnull', True), ('invoice__isnull', False), ('notification_type__in', ['invoice_created', 'invoice_updated']), ('review__isnull', True)), models.Q(('hire__isnull', True), ('invoice__isnull', True), ('notification_type', 'review_created'), ('review__isnull', False)), _connector='OR'), name='notif_type_source_chk'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('notification_type', 'review_created')), fields=('recipient', 'review', 'notification_type'), name='notif_unique_review_created'),
        ),
    ]
